### ISSUE TITLE
Firebase 3: no kid claim in generated token ID

### ISSUE THREAD

**Issue by matbesancon** [wuman/firebase-server-sdk-go#5]
It seems that the library does not work with Firebase 3, the error comes from the verify function in token_verifyer.go, there is no 'kid' key to the get method of the JWS or the interface is not a string.
Minimal working example (firbase 3 project):   https://gist.github.com/mbesancon/ade475435c2f0ccdae215c926712d736#file-firebase-sdk-test-go

The error is already known on other SDKs:  
http://stackoverflow.com/questions/37358105/firebase-3-0-tokens-error-firebase-auth-id-token-has-no-kid-claim    
https://groups.google.com/forum/#!topic/firebase-talk/ajMAi1RSsMA   

And in the firego package:
https://github.com/zabawaba99/fireauth/issues/9

**Comment by wuman** [comment]
I am sure that this library definitely supports Firebase 3 because we are using this in production with Firebase 3.

The error that you are seeing is due to the access token acquired from Firebase not being refreshed.

**Comment by matbesancon** [comment]
The token gets created in the same example snippet right before being tested, why would it need to be refreshed?
